### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by cracky22** [dan-r/HomeAssistant-NissanConnect#103]
Logger: homeassistant.config_entries
Quelle: config_entries.py:761
Erstmals aufgetreten: 14:53:49 (3 Vorkommnisse)
Zuletzt protokolliert: 14:58:06

Error setting up entry EMAIL for nissan_connect
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 60, in async_setup_entry
    await hass.async_add_executor_job(vehicle.fetch_all)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 352, in fetch_all
    self.fetch_cockpit()
    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 850, in fetch_cockpit
    raise ValueError(body['errors'])
ValueError: [{'status': 'Internal Server Error', 'code': '500'}]
```

**Comment by dan-r** [comment]
Could just be a temporary service issue. Does this still happen?

What vehicle are you using?

**Comment by tonutuisk** [comment]
I have X-Trail, Qashqai x2, Juke, Ariya, Townstar - there's no matter, what car. I removed integration and re added, still got message, that Failed to set up. I can tell that this situation has been going on for weeks. Error message is same, as in first message. At same time tried to use app - all ok.

**Comment by cracky22** [comment]
> Could just be a temporary service issue. Does this still happen?
> 
> What vehicle are you using?

Still doesn't work. I own a Townstar all-electric

**Comment by roanstasmota** [comment]
Integration is broken, does not work since last week, same for me.

**Comment by eingeryn** [comment]
I have Nissan Leaf 2023 - no issues. Could it be related with HA OS or Core updates? I have installed latest versions.

**Comment by dan-r** [comment]
Seems to be an issue with all non-Leaf vehicles. Unfortunately thats all I have access to.

However, there was a [recent change](https://github.com/Tobiaswk/dartnissanconnect/commit/0cabf82d90db878630dd540b7a018b2a2404c0cd) made to dartnissanconnect, which a lot of this integration was based on. I'll make that change to this integration and see if it helps.

**Comment by dan-r** [comment]
I've just released version [v0.7.5-beta.2](https://github.com/dan-r/HomeAssistant-NissanConnect/releases/tag/v0.7.5-beta.2). Would those who are having issues mind trying that out?

**Comment by cracky22** [comment]
> I've just released version [v0.7.5-beta.2](https://github.com/dan-r/HomeAssistant-NissanConnect/releases/tag/v0.7.5-beta.2). Would those who are having issues mind trying that out?

Why does HA say that it is still version 1.0.0? It still does not work, by the way.

<img width="791" height="276" alt="Image" src="https://github.com/user-attachments/assets/3877d0cc-d9db-438f-8757-a420f9bbe519" />

## Logs
```
Logger: homeassistant.config_entries
Quelle: config_entries.py:761
Erstmals aufgetreten: 20:04:16 (1 Vorkommnis)
Zuletzt protokolliert: 20:04:16

Error setting up entry EMAIL for nissan_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 60, in async_setup_entry
    await hass.async_add_executor_job(vehicle.fetch_all)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 352, in fetch_all
    self.fetch_cockpit()
    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 850, in fetch_cockpit
    raise ValueError(body['errors'])
ValueError: [{'status': 'Internal Server Error', 'code': '500'}]
```

**Comment by roanstasmota** [comment]
I also tested the 0.7.5.B2 without success.

**Comment by tonutuisk** [comment]
0.7.5.B2 still same error:

Logger: homeassistant.config_entries
Source: config_entries.py:761
First occurred: October 21, 2025 at 21:30:51 (2 occurrences)
Last logged: October 21, 2025 at 21:32:45

Error setting up entry EMAIL for nissan_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 60, in async_setup_entry
    await hass.async_add_executor_job(vehicle.fetch_all)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 352, in fetch_all
    self.fetch_cockpit()
    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 850, in fetch_cockpit
    raise ValueError(body['errors'])
ValueError: [{'status': 'Internal Server Error', 'code': '500'}]

**Comment by dan-r** [comment]
Third time lucky... How about v0.7.5-beta.4?

**Comment by roanstasmota** [comment]
In the beta 4 it behaves different. Below are my output for beta 2 vs beta 4. I have a Townstart EV


0.7.5.B2
2025-10-22 18:07:26.935 INFO (MainThread) [custom_components.nissan_connect] Logging in to service
2025-10-22 18:07:27.561 DEBUG (MainThread) [custom_components.nissan_connect] Finding vehicles
2025-10-22 18:07:28.241 DEBUG (SyncWorker_3) [custom_components.nissan_connect.kamereon.kamereon] Unknown feature 308
2025-10-22 18:07:28.241 DEBUG (SyncWorker_3) [custom_components.nissan_connect.kamereon.kamereon] Active features: [<Feature.MY_CAR_FINDER: '12'>, <Feature.VEHICLE_STATUS_CHECK: '202'>, <Feature.VEHICLE_SOFTWARE_UPDATES: '107'>, <Feature.CHARGING_START: '299'>, <Feature.BATTERY_STATUS: '319'>, <Feature.BREAKDOWN_ASSISTANCE_CALL: '1'>, <Feature.CLIMATE_ON_OFF: '366'>]
2025-10-22 18:07:28.569 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xx@yy.se for nissan_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 60, in async_setup_entry
    await hass.async_add_executor_job(vehicle.fetch_all)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 352, in fetch_all
    self.fetch_cockpit()
    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 850, in fetch_cockpit
    raise ValueError(body['errors'])
ValueError: [{'status': 'Internal Server Error', 'code': '500'}]



v0.7.5-beta.4
2025-10-22 18:10:31.924 INFO (MainThread) [custom_components.nissan_connect] Logging in to service
2025-10-22 18:10:32.511 DEBUG (MainThread) [custom_components.nissan_connect] Finding vehicles
2025-10-22 18:10:33.051 DEBUG (SyncWorker_5) [custom_components.nissan_connect.kamereon.kamereon] Unknown feature 308
2025-10-22 18:10:33.051 DEBUG (SyncWorker_5) [custom_components.nissan_connect.kamereon.kamereon] Active features: [<Feature.MY_CAR_FINDER: '12'>, <Feature.BATTERY_STATUS: '319'>, <Feature.CHARGING_START: '299'>, <Feature.BREAKDOWN_ASSISTANCE_CALL: '1'>, <Feature.VEHICLE_STATUS_CHECK: '202'>, <Feature.VEHICLE_SOFTWARE_UPDATES: '107'>, <Feature.CLIMATE_ON_OFF: '366'>]
2025-10-22 18:10:33.478 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry x@yy.se for nissan_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 60, in async_setup_entry
    await hass.async_add_executor_job(vehicle.fetch_all)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 356, in fetch_all
    self.fetch_battery_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 646, in fetch_battery_status
    self.fetch_battery_status_leaf()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 659, in fetch_battery_status_leaf
    raise ValueError(body['errors'])
ValueError: [{'status': 'Internal Server Error', 'code': '500', 'title': 'BatteryAdapter.getBatteryStatus()'}]

**Comment by tonutuisk** [comment]
I got same error

**Comment by cracky22** [comment]
I got the same error too 😕

**Comment by Roobbbiiiinnnnn** [comment]
Still not working at the latest beta:

Loggare: homeassistant.config_entries
Källa: config_entries.py:761
Inträffade först: 12:42:23 (2 förekomster)
Senast loggade: 12:44:36

Error setting up entry p********mail.com for nissan_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 60, in async_setup_entry
    await hass.async_add_executor_job(vehicle.fetch_all)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 356, in fetch_all
    self.fetch_battery_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 646, in fetch_battery_status
    self.fetch_battery_status_leaf()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 659, in fetch_battery_status_leaf
    raise ValueError(body['errors'])
ValueError: [{'status': 'Internal Server Error', 'code': '500', 'title': 'BatteryAdapter.getBatteryStatus()'}]

**Comment by cracky22** [comment]
@dan-r could this issue from @Roobbbiiiinnnnn be related to my problem? My model is not a Leaf but a Townstar. However, until now, it has not been possible to display the battery status of the Townstar via the HA extension.

**Comment by georgejolliffe** [comment]
Nissan Connect for my Nissan Leaf also failing as of today.

`0.7.4`

```
Error setting up entry NissanConnect Account for nissan_connect
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 976, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 59, in async_setup_entry
    for vehicle in await hass.async_add_executor_job(kamereon_session.fetch_vehicles):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 204, in fetch_vehicles
    '{}v5/users/{}/cars'.format(self.settings['user_base_url'], self.user_id)
                                                                ^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 198, in user_id
    self._user_id = resp.json()['userId']
                    ~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 980, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```


Beta `v0.7.5-beta.4`

```error setting up entry NissanConnect Account for nissan_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 59, in async_setup_entry
    for vehicle in await hass.async_add_executor_job(kamereon_session.fetch_vehicles):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 204, in fetch_vehicles
    '{}v5/users/{}/cars'.format(self.settings['user_base_url'], self.user_id)
                                                                ^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 198, in user_id
    self._user_id = resp.json()['userId']
                    ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'userId'`

**Comment by georgejolliffe** [comment]
Brilliantly....just started working (2024 leaf).

**Comment by tonutuisk** [comment]
Mine shows still error when setting up and in log I see this:

Logger: homeassistant.config_entries
Source: config_entries.py:761
First occurred: 17:40:00 (1 occurrence)
Last logged: 17:40:00

Error setting up entry *****@gmail.com for nissan_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 60, in async_setup_entry
    await hass.async_add_executor_job(vehicle.fetch_all)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 356, in fetch_all
    self.fetch_battery_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 646, in fetch_battery_status
    self.fetch_battery_status_leaf()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 659, in fetch_battery_status_leaf
    raise ValueError(body['errors'])
ValueError: [{'status': 'Internal Server Error', 'code': '500', 'title': 'BatteryAdapter.getBatteryStatus()'}]

**Comment by dan-r** [comment]
The API seems to have changed recently, including for the LEAF. My odometer has stopped increasing this week. I'll need to find some time to reverse engineer the most recent version of the app, but not sure on a timeframe for that.

If anyone experiencing issues has any experience with sniffing app web requests, info on the API endpoints used and what they return would be greatly appreciated too.

**Comment by cracky22** [comment]
> The API seems to have changed recently, including for the LEAF. My odometer has stopped increasing this week. I'll need to find some time to reverse engineer the most recent version of the app, but not sure on a timeframe for that.
> 
> If anyone experiencing issues has any experience with sniffing app web requests, info on the API endpoints used and what they return would be greatly appreciated too.

Doesn't Nissan have API docs?

**Comment by dan-r** [comment]
Nope - completely undocumented and this integration is based entirely around observing what the app does, which is why its a bit trial-and-error especially between different models. The majority of this work was done by [Tobias](https://gitlab.com/tobiaswkjeldsen/dartnissanconnect) for the [My Leaf](https://apps.apple.com/gb/app/my-leaf-for-nissan-ev/id1436701776) app

**Comment by tonutuisk** [comment]
After upgrade to 0.7.5 different error msg

Logger: homeassistant.config_entries
Source: config_entries.py:761
First occurred: 05:07:00 (3 occurrences)
Last logged: 11:50:59

Error setting up entry ***@gmail.com for nissan_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 60, in async_setup_entry
    await hass.async_add_executor_job(vehicle.fetch_all)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 352, in fetch_all
    self.fetch_cockpit()
    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 850, in fetch_cockpit
    raise ValueError(body['errors'])
ValueError: [{'status': 'Forbidden', 'code': '403009', 'title': 'Forbidden action', 'detail': 'Privacy mode currently ON'}]

**Comment by dan-r** [comment]
That error is usually caused by declining the terms when your car starts

**Comment by tonutuisk** [comment]
> That error is usually caused by declining the terms when your car starts

But somehow I end up to this:

<img width="1038" height="352" alt="Image" src="https://github.com/user-attachments/assets/ffa44d3a-7f2f-46d6-abf2-614614cc594c" />
I checked - X-Trail had privacy mode on indeed. Turned it off, refreshed, but no help - still failed to set up. Can't see any of cars in HA

**Comment by cracky22** [comment]
@dan-r i dont have internal server error anymore but i have Not supported Feature instead..
Car Model: Nissan Townstar 

```
Logger: homeassistant.config_entries
Quelle: config_entries.py:798
Erstmals aufgetreten: 18:11:58 (1 Vorkommnis)
Zuletzt protokolliert: 18:11:58

Error setting up entry ****email for nissan_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nissan_connect/__init__.py", line 60, in async_setup_entry
    await hass.async_add_executor_job(vehicle.fetch_all)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 352, in fetch_all
    self.fetch_cockpit()
    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/nissan_connect/kamereon/kamereon.py", line 850, in fetch_cockpit
    raise ValueError(body['errors'])
ValueError: [{'status': 'Not Implemented', 'code': '501', 'title': 'Not supported Feature', 'detail': 'This feature is not technically supported by this gateway'}]
```

**Comment by cracky22** [comment]
@dan-r why did you close this?

**Comment by dan-r** [comment]
@cracky22 with the latest version do you get the same error? Could you please enable debug logging and send over the logs either here or to the email on my GitHub. 

Check for any personal info in there before uploading if posting here.

**Comment by cracky22** [comment]
@dan-r  I'm sorry, it's just my login what isn't working properly
