### ISSUE TITLE
Charging Binary Sensor Not Working - Ariya

### ISSUE THREAD

**Issue by RGx01** [dan-r/HomeAssistant-NissanConnect#77]
**What happened?**
Since release 0.7.0 Binary Sensor Charging does not report charging when charging. Also noting a high number of "Error communicating with API" in logs.

**To Reproduce**
Charge an Ariya and check sensor status after polling.

**Expected behavior**
Binary Sensor should report Charging whilst charging.

**Log Output**
2024-11-13 16:48:01.491 DEBUG (MainThread) [custom_components.nissan_connect.coordinator] Finished fetching Poll Coordinator data in 0.321 seconds (success: True)
2024-11-13 16:48:03.748 DEBUG (MainThread) [custom_components.nissan_connect.coordinator] Finished fetching Update Coordinator data in 2.258 seconds (success: True)
2024-11-13 16:48:09.628 DEBUG (MainThread) [custom_components.nissan_connect.coordinator] Finished fetching Statistics Coordinator data in 2.410 seconds (success: True)
2024-11-13 17:03:03.066 WARNING (MainThread) [custom_components.nissan_connect.coordinator] Error communicating with API
2024-11-13 17:03:03.067 DEBUG (MainThread) [custom_components.nissan_connect.coordinator] Finished fetching Update Coordinator data in 0.025 seconds (success: True)
2024-11-13 17:18:03.766 WARNING (MainThread) [custom_components.nissan_connect.coordinator] Error communicating with API
2024-11-13 17:18:03.767 DEBUG (MainThread) [custom_components.nissan_connect.coordinator] Finished fetching Update Coordinator data in 0.725 seconds (success: True)
2024-11-13 17:33:03.066 WARNING (MainThread) [custom_components.nissan_connect.coordinator] Error communicating with API
2024-11-13 17:33:03.066 DEBUG (MainThread) [custom_components.nissan_connect.coordinator] Finished fetching Update Coordinator data in 0.024 seconds (success: True)
2024-11-13 17:48:01.458 DEBUG (MainThread) [custom_components.nissan_connect.coordinator] Finished fetching Poll Coordinator data in 0.288 seconds (success: True)
2024-11-13 17:48:02.841 DEBUG (MainThread) [custom_components.nissan_connect.coordinator] Finished fetching Update Coordinator data in 1.383 seconds (success: True)
2024-11-13 17:48:02.844 DEBUG (MainThread) [custom_components.nissan_connect.sensor] Updating odometer state
2024-11-13 17:48:11.138 DEBUG (MainThread) [custom_components.nissan_connect.coordinator] Finished fetching Statistics Coordinator data in 1.919 seconds (success: True)
2024-11-13 18:03:02.678 WARNING (MainThread) [custom_components.nissan_connect.coordinator] Error communicating with API
2024-11-13 18:03:02.678 DEBUG (MainThread) [custom_components.nissan_connect.coordinator] Finished fetching Update Coordinator data in 0.636 seconds (success: True)

**Home Assistant Version**
Core
2024.11.1
Supervisor
2024.11.2
Operating System
13.2
Frontend
20241106.2

**Integration Version**
v0.7.0

**Additional context**
polling interval = 60
polling interval while charging = 15
update interval = 15
update interval for stats = 60

**Comment by dan-r** [comment]
The errors communicating with the API seems to be some sort of Nissan issue that I'm getting too.

Does the plugged in sensor update correctly?

**Comment by RGx01** [comment]
Not 100% sure as I've rolled back to v0.6.0. 

My primary use case for using this sensor is to determine which utility meter bucket to put the consumed energy in as we have several vehicles. If I get time this week I'll roll back up and see if I could also use plugged in sensor to do the same job.

**Comment by adammccormack162** [comment]
Ive got the same issue... 

Yes, the plugged in sensor updates correctly on 0.7 - but the charging state doesnt show

**Comment by dan-r** [comment]
I appreciate this is a bit annoying, but could one (or both) of you please install v0.7.1-beta.2 before your next charge. You'll see in the log messages like this:
`2024-11-22 10:16:57.545 WARNING (SyncWorker_12) [custom_components.nissan_connect.kamereon.kamereon] FetchBatteryStatusAriya: {'lastUpdateTime': '2024-11-22T10:12:10Z', 'timeRequiredToFullSlow': 330, 'timeRequiredToFullNormal': 180, 'timeRequiredToFullFast': 90, 'batteryLevel': 92, 'batteryBarLevel': 223, 'rangeHvacOn': 196, 'rangeHvacOff': 203, 'plugStatus': 0, 'chargeStatus': 0, 'chargePower': 1, 'batteryCapacity': 40000}`

If possible, can you please grab one of these messages when you are charging and one when you are not.

Thanks in advance!

**Comment by dan-r** [comment]
Thats really strange - chargingStatus is what I'd expect to update but it doesnt seem to

**Comment by adammccormack162** [comment]
I'd have to check the old version - to see what was coming out on that... (assuming thats what you meant) - but it must do - as it was updating the status to charging

**Comment by pusur333** [comment]
My does also not change. Can I be in any help with logs etc or have you seen the error?

**Comment by RGx01** [comment]
@dan-r do you need anything to help get a resolution to this?

**Comment by dan-r** [comment]
Apologies - I haven't had the time to look into this. It could really do with a developer who owns an Ariya looking at it :) 

The root of the issue is that the changes I made in 0.7.0 (should?) fix the range not showing for the Ariya but seem to have also broken charging binary sensor. This change was to use a different API endpoint to the Leaf.

It seems like we actually need to be hitting both endpoints to keep both working.

**Comment by RGx01** [comment]
> Apologies - I haven't had the time to look into this. It could really do with a developer who owns an Ariya looking at it :)
> 
> The root of the issue is that the changes I made in 0.7.0 (should?) fix the range not showing for the Ariya but seem to have also broken charging binary sensor. This change was to use a different API endpoint to the Leaf.
> 
> It seems like we actually need to be hitting both endpoints to keep both working.

Thanks @dan-r. I wish I could help but I'm not a dev :| I'm just worried that at some point v0.6 will end up being deprecated/left behind. I appreciate the work you've done so far.

**Comment by dan-r** [comment]
I'll try to get a beta out over the weekend and put a message here when its done. Might take a bit of back and forth but shouldn't take too long

**Comment by RGx01** [comment]
@dan-r  looking good so far. I'd like to see what happens when the charge finishes (that won't happen until tomorrow)

<img width="424" alt="Image" src="https://github.com/user-attachments/assets/63e8d029-c58f-44ea-9f3e-d2cbc991bcb4" />

**Comment by dan-r** [comment]
Not a problem, just let me know. Do the range sensors work for you too?

**Comment by RGx01** [comment]
> Not a problem, just let me know. Do the range sensors work for you too?

no they don't

<img width="428" alt="Image" src="https://github.com/user-attachments/assets/717c2435-3573-4c71-9239-dcb01b4a604c" />

<img width="418" alt="Image" src="https://github.com/user-attachments/assets/ff689f16-6f83-4be1-b55d-21a1ad69c536" />

**Comment by RGx01** [comment]
Ariya Plugged in and Ariya Charging seem to reflect each other. The Zappi sensor says the EV is still plugged in (which it is)

<img width="752" alt="Image" src="https://github.com/user-attachments/assets/8c2be0c7-aac1-4334-844a-174a98965dd8" />

**Comment by dididu** [comment]
I'd like to confirm @RGx01 's findings. 
Ariya - I am observing exactly same issues with versions.

**Comment by RGx01** [comment]
Thanks @dan-r , I've put the beta 2 on but the Ariya won't be back till Monday.

Thanks also to @wralb, your analysis was spot on 👍

**Comment by dididu** [comment]
**Looking at v0.7.4-beta.2**

Unplugged - looking **good**:
![Image](https://github.com/user-attachments/assets/ccd88e55-8932-4589-a336-400126096f31)

Plugged in but not charging - looking **good**, although it took a bit of time to show "plugged in"
![Image](https://github.com/user-attachments/assets/cfc042f9-a703-4416-b8a1-111ef73147e5)

Charging - also looking **good**

![Image](https://github.com/user-attachments/assets/fc061dc7-6656-45ec-b649-a8ff77ae3671)

**Comment by dan-r** [comment]
Good to hear its looking good. From experience, I think the service in general is just pretty slow.

So for the range and charge times, there's only one value for the Ariya whereas the Leaf splits them both out into AC on/off and 3kw/6kw.

Charge times seem to change based on if its charging or not, so no idea there. For the range, I'd rather just provide one sensor - do you know whether it looks like the AC on or the AC off range?

**Comment by dididu** [comment]
Good shout @dan-r about reducing duplication. 
I just got the car this month and here in Scotland driving with no AC in Feb is bonkers, so no idea. But given the fact that Ariya has a heat pump, I don't think the difference is going to be that big.

**Comment by dan-r** [comment]
@dididu I'm leaning towards taking that value as AC On, but would you mind checking the range from in the car with heating/cooling on and seeing if it is? For my Leaf (with heat pump) there's only 2 miles difference currently so not a big deal really.

**Comment by dididu** [comment]
@dan-r Ariya doesn't change the GOM with AC on/off.

**Comment by dan-r** [comment]
Ah - that explains the one issue then, thanks for that!

**Comment by wralb** [comment]
Thanks @dan-r 

I agree on Range... I see little difference with AC on or Off neither numerically nor practically. We can definitely simplify the sensors for Ariya.

I also have some observations of "Charge Time", see later.

I made a little test plan and did a sneaky charge... I can corroborate the results from: @dididu as shown here:

![Image](https://github.com/user-attachments/assets/1ee84aa2-1e1a-44e6-a204-da2f33173437)

Regarding charge time, for the first time I think I understand it.  It seems that the value returned by the API is adaptive according to actual charging current, with some sort of default high-current value when unplugged.  This is what happened today, The big jump up happens at charge-start, and the big drop at unplugging.  So, charge time is only really useful during a charge, and there should certainly only be one sensor for the Ariya, perhaps "Charge Time (adaptive)"?

![Image](https://github.com/user-attachments/assets/90633bcb-c390-4ade-ab87-dad37a2bb920)

**Comment by dan-r** [comment]
Thanks for that testing, its really helpful! I've released a new beta that shouldn't change anything except:
1. Only one range number
2. Only one charge speed number

Would you mind testing it out over the weekend? - I'll do the same to make sure I haven't messed up anything for the Leaf/non-Ariyas.

**Comment by natterangell** [comment]
Unlike @dididu, I still get _unknown_ on several of the sensors, even on v.0.7.4-beta.2. 

I should note that the car is brand new (2024 model, FE0-24, Norway), I've had it for less than 24 hours and haven't charged it yet. But the official NissanConnect app shows both estimated range and last updated fields.

![Image](https://github.com/user-attachments/assets/3954edf3-d712-4c66-b9c0-74dc9f50b7ed)

**Comment by dan-r** [comment]
@natterangell what about beta 3?

**Comment by wralb** [comment]
@dan-r Thanks. We're nearly there I think.

Here are my observations of beta2 vs. beta3.

- `Range (AC off)` and `Charge Time (3 kW)` are no-longer exposed - Great 
- `Range (AC on)`  - correctly displays the (single value the Ariya exposes) for range. - Great 
- `Charge Time (6 kW)` is still exposed, but now has the value 'unknown' - ??
- No new "Charge Time" sensors are exposed

I, therefore, cannot see a sensor that exposes Range, unlike in beta 2. I'm not sure what your intention was... to re-use `Charge Time (6 kW)` or to add a new "Charge Time" sensor, but whichever, it doesn't seem to have quite worked:

![Image](https://github.com/user-attachments/assets/e4af9eab-9bbf-49d3-bba3-9dbc30a11316)

**Comment by natterangell** [comment]
beta 3 is as follows. "Last updated" and both range estimates is _unknown_, charge time is _unavailable_ (which might be correct when the car is not connected?). 

![Image](https://github.com/user-attachments/assets/8c2f87c0-0991-4564-9b2a-41d6a487650d)

**Comment by natterangell** [comment]
No, wait. Three sensors were no longer provided by the integration. The following is correct on beta 3 for me, so it seems identical to what @wralb got, except "Range (AC ON)" and "Last updated" are unknown for me. The car has only been active in Nissan's systems for about 24 hour, maybe data needs to propagate somehow(?)

![Image](https://github.com/user-attachments/assets/15bbb9aa-33c8-4057-a0a3-9e4de7787093)

**Comment by dan-r** [comment]
@wralb oops, my bad, typo in the code. How about now with beta 4?

@natterangell odd that it isnt working for you... In beta 4 I've added something in to fallback to the Leaf endpoint if the Ariya one doesnt provide anything. Mind trying this?

**Comment by natterangell** [comment]
Hmm. I don't see any difference. 

![Image](https://github.com/user-attachments/assets/f4edf8fc-4444-4179-8589-32b82c5a19b1)

**Comment by wralb** [comment]
@dan-r Looks good now.

Comparing beta-3 to beta-4:

 - `Charge Time (6kW)` no-longer is exposed
 - `Charge Time (adaptive)` is now available with the expected value
 - All other sensors, as you kindly sorted through these betas, are available and have sensible values

![Image](https://github.com/user-attachments/assets/7a85f9b8-594c-4766-9796-96b32af964a7)

**Comment by dididu** [comment]
@dan-r Morning. 
On beta-4 we got a situation this morning:

![Image](https://github.com/user-attachments/assets/915553c1-cf2d-4158-82fb-808d46423c32)

**Comment by dan-r** [comment]
@dididu hm that's very strange. Would you mind downgrading to 0.6.x temporarily and letting me know if the battery percentage shows for that? If so, it'll be an easy fix, if not it'll require some more investigation.

**Comment by natterangell** [comment]
Is there some pattern to why certain sensors only show values for some users? Could there be API-differences between car firmware versions? As previously, I have a 2024 model firmware verison FE0-24.

**Comment by dididu** [comment]
> [@dididu](https://github.com/dididu) hm that's very strange. Would you mind downgrading to 0.6.x temporarily and letting me know if the battery percentage shows for that? If so, it'll be an easy fix, if not it'll require some more investigation.

Looks like after some driving the battery percentage value appeared again.
It look likely that NissanConnect app just carries the last known value forward, while the integration returns 'unknown' if the api returned nothing. Maybe the integration should persist the last known value to carry it forward as well.

**Comment by dan-r** [comment]
@wralb glad its working for you now!

@natterangell I'm really not sure on this one - I wouldn't have thought it would differ. All supported Leaf models seem to use the same API and present the same data.

@dididu do you see any errors in the logs?

**Comment by RGx01** [comment]
<img width="244" alt="Image" src="https://github.com/user-attachments/assets/2e4d7711-c67e-4cfa-8396-49147aa966cb" />

looking good

**Comment by dan-r** [comment]
Right it looks like for most of you the values are now being provided. I've released v0.7.4 stable now (exactly the same code as beta 4 though).

Because this issue is getting quite long, I'll close it now. If any of you are still having issues, could you please raise it as a new issue with any relevant logs and screenshots. Thank you
